[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "25TysbsxJszh7kSzGMvWvE8VqGDPo82SeRqSxSndNZGF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nacknime/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
